title: Roman's Knowledge Base
email: jromanmartin@gmail.com
description: >- 
  This is my own Knowledge Base with a list of short articles
  with solutions, workarounds, sample code, technical notes, ...
  whatever I have learned in some moment and I don't want to forget.
baseurl: "/knowledge-base"
url: "https://blog.jromanmartin.io"
author: Roman Martin

twitter_username: jromanmartin
github_username: rmarting

google_analytics: UA-179063099-2
show_downloads: true

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-toc
